#!/bin/sh
# nohup: ignore hangup and kill signals

trap "" 1 15  # 1 for hangup, 15 for terminate
if test -t 2>&1  # test if stdout is terminal
then
    echo "Sending output to '/tmp/nohup.out'"
    exec nice -5 $* >>/tmp/nohup.out 2>&1
else
    exec nice -5 $* 2>&1
fi

